package com.adshield.app.root

import android.content.Context
import android.os.Build
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.util.concurrent.TimeUnit

/**
 * Optional root mode. Writes the merged blocklists into the system hosts file so that filtering
 * applies to every app, including ones that use their own or encrypted DNS, and keeps working
 * while the VPN is off.
 *
 * Two strategies are attempted: a bind mount from /data/local/tmp (works on modern
 * system-as-root devices) and a direct write after remounting / read-write (older devices).
 */
object RootHostsManager {

    private const val SYSTEM_HOSTS = "/system/etc/hosts"
    private const val STAGED_HOSTS = "/data/local/tmp/adshield_hosts"

    suspend fun isRootAvailable(): Boolean = withContext(Dispatchers.IO) {
        val result = su("id")
        result.ok && result.output.contains("uid=0")
    }

    suspend fun install(context: Context, domains: Set<String>): Result<Int> =
        withContext(Dispatchers.IO) {
            runCatching {
                if (domains.isEmpty()) throw IllegalStateException("no domains to write")

                val staged = File(context.filesDir, "hosts_staged")
                writeHosts(staged, domains)

                val backup = File(context.filesDir, "hosts_backup")
                if (!backup.exists() || backup.length() == 0L) {
                    val copied = su("cp -f $SYSTEM_HOSTS ${backup.absolutePath}")
                    if (!copied.ok) throw IllegalStateException(copied.output)
                }

                val bind = su(
                    "cp -f ${staged.absolutePath} $STAGED_HOSTS && " +
                        "chmod 644 $STAGED_HOSTS && " +
                        "mount --bind $STAGED_HOSTS $SYSTEM_HOSTS"
                )
                if (!bind.ok) {
                    val direct = su("mount -o rw,remount /system && cp -f ${staged.absolutePath} $SYSTEM_HOSTS")
                    if (!direct.ok) {
                        throw IllegalStateException(direct.output.ifBlank { bind.output })
                    }
                }
                domains.size
            }
        }

    suspend fun restore(context: Context): Result<Unit> = withContext(Dispatchers.IO) {
        runCatching {
            su("umount $SYSTEM_HOSTS")
            val backup = File(context.filesDir, "hosts_backup")
            if (backup.exists() && backup.length() > 0L) {
                val copied = su("cp -f ${backup.absolutePath} $SYSTEM_HOSTS")
                if (!copied.ok) throw IllegalStateException(copied.output)
            }
        }
    }

    private fun writeHosts(file: File, domains: Set<String>) {
        file.bufferedWriter().use { writer ->
            writer.write("# Generated by AdShield - do not edit by hand\n")
            writer.write("127.0.0.1 localhost\n")
            writer.write("::1 localhost\n")
            for (domain in domains) {
                writer.write("0.0.0.0 ")
                writer.write(domain)
                writer.write("\n")
                writer.write(":: ")
                writer.write(domain)
                writer.write("\n")
            }
        }
    }

    private const val SU_TIMEOUT_SECONDS = 30L

    private data class ShellResult(val ok: Boolean, val output: String)

    private fun su(command: String): ShellResult = runCatching {
        val process = ProcessBuilder("su", "-c", command)
            .redirectErrorStream(true)
            .start()
        val output = process.inputStream.bufferedReader().use { it.readText() }.trim()
        // Process.waitFor(long, TimeUnit) only exists from API 26, so older devices use the
        // plain blocking waitFor() instead.
        val finished = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            process.waitFor(SU_TIMEOUT_SECONDS, TimeUnit.SECONDS)
        } else {
            process.waitFor()
            true
        }
        if (!finished) process.destroy()
        ShellResult(finished && process.exitValue() == 0, output)
    }.getOrElse { ShellResult(false, it.message ?: "su failed") }
}
